//	*************************************************
//	* Datex-Ohmeda Inc.
//	* Ohmeda Drive
//	* PO Box 7550
//	* Madison, WI 53707-7550
//	*
//	* Copyright 2000, Datex-Ohmeda, Inc.
//	*
//	* Archive Name:              $Archive: /DisplayComputer/Software/DCCommonSnapshot/Iris/Source/RoseSrc/LinkTestMessage.h $
//	* Working File Name:         $Workfile: LinkTestMessage.h $
//	*
//	* Version:                   $Revision: 1.1.1.1 $
//	*
//	* Last Modification Time:    $Modtime: 3/24/03 11:54a $
//	* Author:                    $Author: aa027762 $
//	*
//	*************************************************

#ifndef LinkTestMessage_h
#define LinkTestMessage_h 1

// Message
#include "Message.h"
	// The number of bytes in the serialized message that are added by the 
	// this specialization of Message
#define LINK_TEST_SERIALIZED_MSG_SIZE 8
//	Internal IRIS message used to send a response to a link
//	check.

class LinkTestMessage : public Message  //## Inherits: <unnamed>%39F894650321
{

  public:
    // Constructors (generated)
      LinkTestMessage();

    // Destructor (generated)
      ~LinkTestMessage();

       int getID ();

      int deserialize (IRIS_UBYTE *bufPtr, IRIS_UINT32 length);

      int serialize (IRIS_UBYTE *bufPtr);

    // Data Members for Class Attributes

      //	This is the autogenerated compatibility code for the
      //	IRIS node.
      IRIS_UINT32 compatabilityCode;

      //	Must be a unique identifier for the living IRIS_Node
      //	object.  Used for loopback detection.
      IRIS_UINT32 controlNumber;

  protected:

  private:

};
// Class LinkTestMessage 

#endif
